### ISSUE TITLE
Issue while dispatching event in sfapi when machine is locked

### ISSUE THREAD

**Issue by SushantKhandagale** [hirsivaja/sfapi#1]
I am automating the flex application using Selenium Flex API, everything works fine but If machine is locked then sometimes below mentioned line doesn't work.  It returns true but somehow the action on the click of button doesn't show up.

button.dispatchEvent(new MouseEvent(MouseEvent.CLICK))

**Comment by hirsivaja** [comment]
Can you elaborate on your setup? If you are using a Windows machine then you can try running the tests with Remote Desktop Connection if you need to lock the computer.

**Comment by hirsivaja** [comment]
Closing. More information needed to solve
